[package]
name = "neuros"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand ="0.8.5"
ndarray = "0.15.0"
linfa ="0.6.1"

sefar = {path =  "/home/sd/Documents/Rust_apps/sefar_v002", features =["show_report"]}